version: "3.5"
services:
  front:
    image: kosta/front
    build: .
    container_name: "kosta-front"
    command: bash -c "pwd && ls && nginx"
    ports:
      - "83:80"
    environment:
      - BASE_URL="http://ingies.net:8200"
