version: "3.5"
services:
  front:
    image: node:14
    command: npm run start
    build: .
    container_name: 'front'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0

